### ISSUE TITLE
The node has attr have not text content.

### ISSUE THREAD

**Issue by hyhkjiy** [stackerzzq/xj2go#3]
I have a xml like this:
```xml
<A>
    <B>some text...</B>
    <C ID="1">some text...</C>
    <D ID="2">
        <E>some text...</E>
    </D>
</A>
```

the result:
```go
type A struct {
	B string `xml:"B"`
	C C      `xml:"C,attr"`
	D D      `xml:"D,attr"`
}
type C struct {
	ID string `xml:"ID,attr"`
}
type D struct {
	ID string `xml:"ID,attr"`
	E  string `xml:"E"`
}

```

Node "C" have attribute "ID" and some text content, but the struct "C" only has attribute "ID" and have not text content.

**Comment by stackerzzq** [comment]
@hyhkjiy Sorry for late answer, I have checked this situation and previously version already satisfy this.
