### ISSUE TITLE
Not able to install this tool. 

### ISSUE THREAD

**Issue by Aravindekanath** [stackerzzq/xj2go#7]
Hi,

When I try to install this tool, I am not able to do so..
I even cloned this code and tried running the sample file but same issue occurred. Let me know the solution for it

# go get -u -v github.com/wk30/xj2go/cmd/...
verifying github.com/wk30/xj2go@v0.0.0-20181223045710-4042c1bc2ba9/go.mod: checksum mismatch
        downloaded: h1:WLVuEQ21+AMkIXTaAfOTIIpJ+cYmXdi5ocziIfKhjVg=
        go.sum:     h1:AzoaAEzQwR7h97hUbt9kPWYG+jwD7GbxS9C1YOxYbYA=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.

**Comment by gigdoug** [comment]
Hi,

I am also getting the same errors after doing both steps as described above.  Looks like a file was slipped in or something.
